/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  BadBeaconNotContract,
  BadBeaconNotContractInterface,
} from "../BadBeaconNotContract";

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50604e80601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80635c60da1b14602d575b600080fd5b604080516001815290519081900360200190f3fea164736f6c6343000809000a";

type BadBeaconNotContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BadBeaconNotContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BadBeaconNotContract__factory extends ContractFactory {
  constructor(...args: BadBeaconNotContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BadBeaconNotContract> {
    return super.deploy(overrides || {}) as Promise<BadBeaconNotContract>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): BadBeaconNotContract {
    return super.attach(address) as BadBeaconNotContract;
  }
  connect(signer: Signer): BadBeaconNotContract__factory {
    return super.connect(signer) as BadBeaconNotContract__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BadBeaconNotContractInterface {
    return new utils.Interface(_abi) as BadBeaconNotContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BadBeaconNotContract {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BadBeaconNotContract;
  }
}
