/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ERC165Mock, ERC165MockInterface } from "../ERC165Mock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060ce8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806301ffc9a714602d575b600080fd5b60666038366004607a565b7fffffffff00000000000000000000000000000000000000000000000000000000166301ffc9a760e01b1490565b604051901515815260200160405180910390f35b600060208284031215608b57600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811460ba57600080fd5b939250505056fea164736f6c6343000809000a";

type ERC165MockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC165MockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC165Mock__factory extends ContractFactory {
  constructor(...args: ERC165MockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC165Mock> {
    return super.deploy(overrides || {}) as Promise<ERC165Mock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC165Mock {
    return super.attach(address) as ERC165Mock;
  }
  connect(signer: Signer): ERC165Mock__factory {
    return super.connect(signer) as ERC165Mock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC165MockInterface {
    return new utils.Interface(_abi) as ERC165MockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC165Mock {
    return new Contract(address, _abi, signerOrProvider) as ERC165Mock;
  }
}
