/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  Implementation3,
  Implementation3Interface,
} from "../Implementation3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101b6806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630ff4c91614610046578063552410771461006b5780638129fc1c14610080575b600080fd5b61005961005436600461016a565b610088565b60405190815260200160405180910390f35b61007e61007936600461016a565b600155565b005b61007e61009e565b6000816001546100989190610183565b92915050565b600054610100900460ff166100b95760005460ff16156100bd565b303b155b6101335760405162461bcd60e51b815260206004820152602e60248201527f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160448201527f647920696e697469616c697a6564000000000000000000000000000000000000606482015260840160405180910390fd5b600054610100900460ff16158015610155576000805461ffff19166101011790555b8015610167576000805461ff00191690555b50565b60006020828403121561017c57600080fd5b5035919050565b600082198211156101a457634e487b7160e01b600052601160045260246000fd5b50019056fea164736f6c6343000809000a";

type Implementation3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation3__factory extends ContractFactory {
  constructor(...args: Implementation3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Implementation3> {
    return super.deploy(overrides || {}) as Promise<Implementation3>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Implementation3 {
    return super.attach(address) as Implementation3;
  }
  connect(signer: Signer): Implementation3__factory {
    return super.connect(signer) as Implementation3__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation3Interface {
    return new utils.Interface(_abi) as Implementation3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Implementation3 {
    return new Contract(address, _abi, signerOrProvider) as Implementation3;
  }
}
