/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  Implementation4,
  Implementation4Interface,
} from "../Implementation4";

const _abi = [
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610166806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80632096525514610047578063552410771461005c5780638129fc1c14610071575b60018055005b60015460405190815260200160405180910390f35b61006f61006a366004610140565b600155565b005b61006f600054610100900460ff1661008f5760005460ff1615610093565b303b155b6101095760405162461bcd60e51b815260206004820152602e60248201527f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160448201527f647920696e697469616c697a6564000000000000000000000000000000000000606482015260840160405180910390fd5b600054610100900460ff1615801561012b576000805461ffff19166101011790555b801561013d576000805461ff00191690555b50565b60006020828403121561015257600080fd5b503591905056fea164736f6c6343000809000a";

type Implementation4ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation4ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation4__factory extends ContractFactory {
  constructor(...args: Implementation4ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Implementation4> {
    return super.deploy(overrides || {}) as Promise<Implementation4>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Implementation4 {
    return super.attach(address) as Implementation4;
  }
  connect(signer: Signer): Implementation4__factory {
    return super.connect(signer) as Implementation4__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation4Interface {
    return new utils.Interface(_abi) as Implementation4Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Implementation4 {
    return new Contract(address, _abi, signerOrProvider) as Implementation4;
  }
}
