/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ReentrancyAttack,
  ReentrancyAttackInterface,
} from "../ReentrancyAttack";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "data",
        type: "bytes4",
      },
    ],
    name: "callSender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101da806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80630a2df1ed14610030575b600080fd5b61004361003e366004610149565b610045565b005b60408051600481526024810182526020810180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff167fffffffff000000000000000000000000000000000000000000000000000000008516179052905160009133916100ae9190610192565b6000604051808303816000865af19150503d80600081146100eb576040519150601f19603f3d011682016040523d82523d6000602084013e6100f0565b606091505b50509050806101455760405162461bcd60e51b815260206004820152601d60248201527f5265656e7472616e637941747461636b3a206661696c65642063616c6c000000604482015260640160405180910390fd5b5050565b60006020828403121561015b57600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811461018b57600080fd5b9392505050565b6000825160005b818110156101b35760208186018101518583015201610199565b818111156101c2576000828501525b50919091019291505056fea164736f6c6343000809000a";

type ReentrancyAttackConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyAttackConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyAttack__factory extends ContractFactory {
  constructor(...args: ReentrancyAttackConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ReentrancyAttack> {
    return super.deploy(overrides || {}) as Promise<ReentrancyAttack>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ReentrancyAttack {
    return super.attach(address) as ReentrancyAttack;
  }
  connect(signer: Signer): ReentrancyAttack__factory {
    return super.connect(signer) as ReentrancyAttack__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyAttackInterface {
    return new utils.Interface(_abi) as ReentrancyAttackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentrancyAttack {
    return new Contract(address, _abi, signerOrProvider) as ReentrancyAttack;
  }
}
