exports.errorCodes = {
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  DISPUTE_NOT_FOUND: "DISPUTE_NOT_FOUND",
  DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
  TRIP_NOT_FOUND: "TRIP_NOT_FOUND",
  SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  MISSING_VAL: "MISSING_VAL",
  UNAUTHORIZED: "UNAUTHORIZED_ACCESS",
  VALUE_NOT_ACCEPTABLE: "VALUE_NOT_ACCEPTABLE",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  INCORRECT_FORMAT: "INCORRECT_FORMAT",
  NOT_UNIQUE: "NOT-UNIQUE",
};
